### ISSUE TITLE
Make a client and resource server examples

### ISSUE THREAD

**Issue by devabe** [OhadR/spring-oAuth2-SAML-integration#3]
Hello Ohad,

   It's @devabe

   Can you please make :

- some remote resource server that validates a token, that it receives from the client, against the authorization server

- some client that redirects to Auth server for authentication, receives token for the client and calls the resource server to get some resource

 Thanks,
 devabe

**Comment by OhadR** [comment]
the scope of this specific repository is to demonstrate the bridge between oAuth and SAML. 

the client and resource-server are out of scope here... 
however, after the recent migration to Spring latest major versions, it should be straight forward. In addition, I have another repository, https://github.com/OhadR/oAuth2-sample, with the same Spring versions, that demonstrate all 3 oAuth parties - you can use the client and resource server from that repo.

you can feel free to collaborate and add some functionality there...

Hope that helps.
