### ISSUE TITLE
where is entity id in your code. you had commented lines in saml-securityContext.xml

### ISSUE THREAD

**Issue by sanjayMantati** [OhadR/spring-oAuth2-SAML-integration#4]
And it giving me an error from sso circle that "Reason: Issuer in Request is invalid."

**Comment by OhadR** [comment]
please paste the error that you get. when (in what step) do you get this error?

**Comment by sanjayMantati** [comment]
when is start the project and hit its context path. then it redirect to ssocircle and give me above error.

**Comment by sanjayMantati** [comment]
Error occurred

Reason: Issuer in Request is invalid.

Please enable the additional debug option in "My Debug".
Detailed trace information only available with paid accounts.
Check our plans.

**Comment by OhadR** [comment]
it is irreproducible on my env.
when you take the project as-is and try to run it (see the README), do you still get the error?

**Comment by sanjayMantati** [comment]
Here is the[https://drive.google.com/file/d/1Tc0ZuZ4k5k42Ptgx8Fv92GFGFJb3ZJPB/view?usp=sharing](link) of log when in run mvn tomcat7:run.
I have just changed database credentials and ohad.js file path to may local one.

**Comment by OhadR** [comment]
> Here is the [link](https://drive.google.com/file/d/1Tc0ZuZ4k5k42Ptgx8Fv92GFGFJb3ZJPB/view?usp=sharing) of log when in run mvn tomcat7:run.
> I have just changed database credentials and ohad.js file path to may local one.

awesome, thanks. can you elight me where is the error that you talked about? (i get the exact same logs)

**Comment by sanjayMantati** [comment]
The problem is there are no errors in logs but when i hit "http://localhost:8081/oauth-2-saml", it redirects to ssocircle and produce it gives this page.[image of ssocircle](https://drive.google.com/file/d/1yKjYhpUKziZldb_Qd-Om6DsdWm1xxJC2/view?usp=sharing)

**Comment by sanjayMantati** [comment]
i found some thing in database [link](https://drive.google.com/file/d/15DrHT8xmpl6k2j0QPX0I5GH2EZUZ2cgE/view?usp=sharing)

**Comment by OhadR** [comment]
> when i start the project and hit its context path. then it redirect to ssocircle and give me above error.

you said you get the error upon startup...
i will take a look. i don;t have ssocircle env running so it might take some time.
did you try to un-comment the "entity-id" from the XML?

**Comment by sanjayMantati** [comment]
i un-comment the entity-id from the xml and changed it to com.ohadexamples11 and then uploaded it's metadata to ssocircle. But when i complete authenticate through ssocircle, it shows me like this [link](https://drive.google.com/open?id=1yKjYhpUKziZldb_Qd-Om6DsdWm1xxJC2)

**Comment by OhadR** [comment]
i guess that you have to enter the real issuer ID that you get from ssc-circle. com.ohadr is just for example, and should be replaced in real systems.

**Comment by sanjayMantati** [comment]
i put com.ohadexamples11 as entitId at  both side. at sso-circle and in project

**Comment by sanjayMantati** [comment]
where i will get oauth2 token? Does it will show me in database table after saml authentication?

**Comment by OhadR** [comment]
did u solve the first problem?
_______________________________
Ohad Redlich [image: linked-in with me]
<http://il.linkedin.com/in/ohadredlich/>[image: Join my Facebook Page]
<https://www.facebook.com/ohadr.photography>  <https://github.com/OhadR>
<http://stackoverflow.com/users/421642/ohadr>

**Comment by sanjayMantati** [comment]
nop. i didn't. but please tell me where i will found the token, in table or somewhere else.

**Comment by OhadR** [comment]
it could be better to ask each question in a separate issue. (so it can help others, in the future).

However, I use org.springframework.security.oauth2.provider.code.JdbcAuthorizationCodeServices to store the token in the DB.

**Comment by sanjayMantati** [comment]
Ok, I have changed the assertionConsumerIndex because its value was 1 which user HTTP-artifact in SP's metadata but ssocircle uses HTTP-Post. for that assertionConsumerIndex should be 0. but now it's giving me an error [Link](https://drive.google.com/open?id=1k8IyficJ3EoE_CJQLcxA8fiU0X6AnwH8)

**Comment by OhadR** [comment]
from: https://github.com/spring-projects/spring-security-oauth/issues/625

> The problem is that in Spring Security 4.x XML configuration uses expressions by default and IS_AUTHENTICATED_FULLY is not the expression syntax. Either disable expressions using <http use-expressions="false"> or replace IS_AUTHENTICATED_FULLY withfullyAuthenticated`.

**Comment by OhadR** [comment]
feel free to create a pull request with the fix :)
