### ISSUE TITLE
Where do you invoke the Oauth authentication provider?

### ISSUE THREAD

**Issue by bogados** [OhadR/spring-oAuth2-SAML-integration#5]
I was looking at your code, I am creating the same integration, but I'm having trouble when calling the same microservice (different endpoint) to obtain the token and send it to the frontend.
I also need different grant types. For example the client_id and password are grant types implemented in the Spring security Oauth module. 
I don't know if this makes any sense or if you can give me your opinion on this implementation.

**Comment by OhadR** [comment]
can u explain a bit more about your topology?

**Comment by bogados** [comment]
I am using an idp that authenticates and saml.
But I need to authorize different clients.

So, I had and IDP that authenticates, a frontend, an authorization server (That receives the assertion from the idp) and later I have a resource server.

I can't figure out how to implement your solution in order to receive the assertion and generate the token

**Comment by OhadR** [comment]
not sure why do u need to combine oAuth and SAML. Did you read the [motivation ](https://github.com/OhadR/spring-oAuth2-SAML-integration#motivation)section in the README?

**Comment by bogados** [comment]
I need to combine this because I have an IdP that can't be used for authorizations, just only authentication. But, I have a lot of applications that I need to authorize (To use my resource server or Service provider how you want to say it).

**Comment by OhadR** [comment]
I am sure that you are well familiar with SAML, but it sounds weird to me that you cannot authorize different SP's... 

https://www.varonis.com/blog/what-is-saml/

https://stackoverflow.com/questions/31512647/spring-security-saml-sso-authorizing-multiple-resources

**Comment by bogados** [comment]
I signed an NDA and can't give away too much details, but it just won't work on the current solution design. Just only I need to know how you create the SSO endpoint to get the token after the authentication that comes from the IdP

**Comment by OhadR** [comment]
in the project's README, there is a [link to the document ](https://www.codeproject.com/Articles/598581/How-to-integrate-Spring-oAuth2-with-Spring-SAML)that I have written a while back. I believe that the **"Integrating Spring’s oAuth and SAML"** section answers your question.

**Comment by OhadR** [comment]
does it help? Did you find the answer there? If so, can this issue be closed?

**Comment by bogados** [comment]
The article was helpful. Thanks for your patience. I close the issue
