### ISSUE TITLE
error getting dependency com.jamonapi:jamon:jar:2.4

### ISSUE THREAD

**Issue by bahrar** [OhadR/spring-oAuth2-SAML-integration#6]
* when i tried to install (mvn clean install)
i got this error:

`
[ERROR] Failed to execute goal on project oauth-2-saml: Could not resolve  dependencies for project com.ohadr:oauth-2-saml:war:1.6.0-RELEASE: Failed to collect dependencies at com.jamonapi:jamon:jar:2.4: Failed to read artifact descriptor for com.jamonapi:jamon:jar:2.4: Could not transfer artifact com.jamonapi:jamon:pom:2.4 from/to spring-milestone (http://maven.springframework.org/milestone): Access denied to: http://maven.springframework.org/milestone/com/jamonapi/jamon/2.4/jamon-2.4.pom -> [Help 1]
`

* i solved it by updating jamon to version 2.81 

		<dependency>
			<groupId>com.jamonapi</groupId>
			<artifactId>jamon</artifactId>
			<version>2.81</version>
		</dependency>

thanks

**Comment by OhadR** [comment]
thanks for LMK. 
you are correct, there was a mis-configuration in the pom.xml. i have fixed it.

thanks!
